# Generated by Django 6.0.4 on 2026-04-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biggest_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_bonus_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='player', max_length=15),
        ),
    ]
