# Generated by Django 6.0.5 on 2026-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_user_biggest_win_user_daily_bonus_streak_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('es', 'Español')], default='ru', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='user_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='user_level_at_least_1'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('experience__gte', 0)), name='user_experience_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('total_games__gte', 0)), name='user_total_games_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('total_wins__gte', 0)), name='user_total_wins_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('total_losses__gte', 0)), name='user_total_losses_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('biggest_win__gte', 0)), name='user_biggest_win_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('daily_bonus_streak__gte', 0)), name='user_streak_non_negative'),
        ),
    ]
